device_name = "LaserCam"

# If logfile is defined, log temperature readings to the file
log_file  = "/home/pi/temperature.log"
log_file_rotate_size = 100000000 #bytes
#log_level = "DEBUG"

# How often do we want to poll the temperature (in seconds)? Default = 1
poll_rate = 1

# Set some warning values for temperature (in Celsius)
[temp]
max = 100
min = 0

# Raspberry Pi SPI Config
[pi]
# Connect Method can be either "SOFTWARE" (default) or "HARDWARE"
connect_method = "SOFTWARE"
# Software SPI
CLK = 25
CS  = 24
DO  = 18
# Hardware SPI
SPI_PORT   = 0
SPI_DEVICE = 0

# HipChat Configuration Settings
[hipchat]
#token = "YOUR TOKEN"
#room  = "YOUR ROOM ID"
#notify_names = "@Name1 @Name2"
